on: [push]

jobs:
  ci_job:
    runs-on: ubuntu-latest
    name: Test that the game can be compiled
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Test Linux build using Docker
        run: docker build . -f extra/docker/Dockerfile -t game_test
